/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ricardo Garnica (https://sketchfab.com/rjgarnicap)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-globe-atlas-cd178e25a0e6436380b15fc1539a25f2
Title: Earth Globe - Atlas
*/

"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const Globe = React.memo(function Globe(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/globe-transformed.glb");

  const ref = useRef()
  
  useFrame((_, delta) => {
  
    ref.current.rotation.y += 0.5 * delta
  })
  

  return (
    <group 
      {...props} 
      dispose={null}
      ref={ref}
      position={[ 0, -0.9, 0]}
      scale={[2.0, 2.0, 2.0]}
      rotation={[0, 0, 0.]}
      >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.heightmap_ref_group}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
});
export default Globe;
useGLTF.preload('/models/globe-transformed.glb');